### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by paulomcnally** [moneppo/node-pocketsphinx#5]
```
npm install pocketsphinx
-
> segfault-handler@0.2.4 install /Users/paulomcnally/develop/test/audio/node_modules/pocketsphinx/node_modules/segfault-handler
> node-gyp rebuild

  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/segfault-handler.node
  SOLINK_MODULE(target) Release/segfault-handler.node: Finished

> pocketsphinx@1.0.0 install /Users/paulomcnally/develop/test/audio/node_modules/pocketsphinx
> node-gyp rebuild

  CXX(target) Release/obj.target/PocketSphinx/src/Factory.o
  CXX(target) Release/obj.target/PocketSphinx/src/Recognizer.o
../src/Recognizer.cpp:23:67: error: use of undeclared identifier 'MODELDIR'
  tpl->Set(String::NewSymbol("modelDirectory"), String::NewSymbol(MODELDIR));
                                                                  ^
../src/Recognizer.cpp:73:97: error: use of undeclared identifier 'MODELDIR'
  ...String::NewSymbol(MODELDIR "/hmm/en_US/hub4wsj_sc_8k")));
                       ^
../src/Recognizer.cpp:74:95: error: use of undeclared identifier 'MODELDIR'
  ...String::NewSymbol(MODELDIR "/lm/en_US/hub4.5000.DMP")));
                       ^
../src/Recognizer.cpp:75:99: error: use of undeclared identifier 'MODELDIR'
  ...String::NewSymbol(MODELDIR "/lm/en_US/cmu07a.dic")));
                       ^
../src/Recognizer.cpp:117:16: error: use of undeclared identifier
      'ps_set_keyphrase'
  int result = ps_set_keyphrase(instance->ps, *name, *keyphrase);
               ^
../src/Recognizer.cpp:141:16: error: use of undeclared identifier 'ps_set_kws'
  int result = ps_set_kws(instance->ps, *name, *file);
               ^
../src/Recognizer.cpp:165:16: error: use of undeclared identifier
      'ps_set_jsgf_file'
  int result = ps_set_jsgf_file(instance->ps, *name, *file);
               ^
../src/Recognizer.cpp:189:16: error: use of undeclared identifier
      'ps_set_lm_file'
  int result = ps_set_lm_file(instance->ps, *name, *file);
               ^
../src/Recognizer.cpp:199:43: error: use of undeclared identifier
      'ps_get_search'; did you mean 'ps_get_feat'?
  Local<Value> search = String::NewSymbol(ps_get_search(instance->ps));
                                          ^~~~~~~~~~~~~
                                          ps_get_feat
/usr/local/Cellar/cmu-pocketsphinx/0.8/include/pocketsphinx/pocketsphinx.h:190:9: note: 
      'ps_get_feat' declared here
feat_t *ps_get_feat(ps_decoder_t *ps);
        ^
../src/Recognizer.cpp:199:43: error: cannot initialize a parameter of type
      'const char *' with an rvalue of type 'feat_t *' (aka 'feat_s *')
  Local<Value> search = String::NewSymbol(ps_get_search(instance->ps));
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/paulomcnally/.node-gyp/0.10.32/deps/v8/include/v8.h:1235:55: note: 
      passing argument to parameter 'data' here
  V8EXPORT static Local<String> NewSymbol(const char* data, int length = -1);
                                                      ^
../src/Recognizer.cpp:209:3: error: use of undeclared identifier 'ps_set_search'
  ps_set_search(instance->ps, *search);
  ^
11 errors generated.
make: *** [Release/obj.target/PocketSphinx/src/Recognizer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/paulomcnally/.nvm/v0.10.32/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/paulomcnally/.nvm/v0.10.32/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/paulomcnally/develop/test/audio/node_modules/pocketsphinx
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! pocketsphinx@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@1.0.0 install script.
npm ERR! This is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/paulomcnally/.nvm/v0.10.32/bin/node" "/Users/paulomcnally/.nvm/v0.10.32/bin/npm" "install" "pocketsphinx"
npm ERR! cwd /Users/paulomcnally/develop/test/audio
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by nshmyrev** [comment]
For those who wonder what the issue is, make sure you installed latest pocketsphinx, not cmu-pocketsphinx-0.8.
