### ISSUE TITLE
Having trouble running demo

### ISSUE THREAD

**Issue by seandoyle** [moneppo/node-pocketsphinx#6]
I'm using the latest code (pocketsphinx, sphinxbase, and node-pocketsphinx) from git in Ubuntu 14.04 with Node v0.10.36. When I try to run 'node index.js' from the demo directory I get an error in at sphinx.addGrammarSearch. I'm very new to node so it's very possible I'm doing something wrong.

Thanks for any help.

$ node index.js
Listening on port 3000
INFO: cmd_ln.c(697): Parsing command line:
\
	-hmm /usr/local/share/pocketsphinx/model/en-us/en-us \
	-dict /usr/local/share/pocketsphinx/model/en-us/cmudict-en-us.dict \
	-samprate 16000 \
	-nfft 2048 

Current configuration:
[NAME]		[DEFLT]		[VALUE]
-agc		none		none
-agcthresh	2.0		2.000000e+00
-allphone			
-allphone_ci	no		no
-alpha		0.97		9.700000e-01
-ascale		20.0		2.000000e+01
-aw		1		1
-backtrace	no		no
-beam		1e-48		1.000000e-48
-bestpath	yes		yes
-bestpathlw	9.5		9.500000e+00
-ceplen		13		13
-cmn		current		current
-cmninit	8.0		8.0
-compallsen	no		no
-debug				0
-dict				/usr/local/share/pocketsphinx/model/en-us/cmudict-en-us.dict
-dictcase	no		no
-dither		no		no
-doublebw	no		no
-ds		1		1
-fdict				
-feat		1s_c_d_dd	1s_c_d_dd
-featparams			
-fillprob	1e-8		1.000000e-08
-frate		100		100
-fsg				
-fsgusealtpron	yes		yes
-fsgusefiller	yes		yes
-fwdflat	yes		yes
-fwdflatbeam	1e-64		1.000000e-64
-fwdflatefwid	4		4
-fwdflatlw	8.5		8.500000e+00
-fwdflatsfwin	25		25
-fwdflatwbeam	7e-29		7.000000e-29
-fwdtree	yes		yes
-hmm				/usr/local/share/pocketsphinx/model/en-us/en-us
-input_endian	little		little
-jsgf				
-keyphrase			
-kws				
-kws_plp	1e-1		1.000000e-01
-kws_threshold	1		1.000000e+00
-latsize	5000		5000
-lda				
-ldadim		0		0
-lifter		0		0
-lm				
-lmctl				
-lmname				
-logbase	1.0001		1.000100e+00
-logfn				
-logspec	no		no
-lowerf		133.33334	1.333333e+02
-lpbeam		1e-40		1.000000e-40
-lponlybeam	7e-29		7.000000e-29
-lw		6.5		6.500000e+00
-maxhmmpf	30000		30000
-maxwpf		-1		-1
-mdef				
-mean				
-mfclogdir			
-min_endfr	0		0
-mixw				
-mixwfloor	0.0000001	1.000000e-07
-mllr				
-mmap		yes		yes
-ncep		13		13
-nfft		512		2048
-nfilt		40		40
-nwpen		1.0		1.000000e+00
-pbeam		1e-48		1.000000e-48
-pip		1.0		1.000000e+00
-pl_beam	1e-10		1.000000e-10
-pl_pbeam	1e-10		1.000000e-10
-pl_pip		1.0		1.000000e+00
-pl_weight	3.0		3.000000e+00
-pl_window	5		5
-rawlogdir			
-remove_dc	no		no
-remove_noise	yes		yes
-remove_silence	yes		yes
-round_filters	yes		yes
-samprate	16000		1.600000e+04
-seed		-1		-1
-sendump			
-senlogdir			
-senmgau			
-silprob	0.005		5.000000e-03
-smoothspec	no		no
-svspec				
-tmat				
-tmatfloor	0.0001		1.000000e-04
-topn		4		4
-topn_beam	0		0
-toprule			
-transform	legacy		legacy
-unit_area	yes		yes
-upperf		6855.4976	6.855498e+03
-uw		1.0		1.000000e+00
-vad_postspeech	50		50
-vad_prespeech	10		10
-vad_threshold	2.0		2.000000e+00
-var				
-varfloor	0.0001		1.000000e-04
-varnorm	no		no
-verbose	no		no
-warp_params			
-warp_type	inverse_linear	inverse_linear
-wbeam		7e-29		7.000000e-29
-wip		0.65		6.500000e-01
-wlen		0.025625	2.562500e-02

INFO: cmd_ln.c(697): Parsing command line:
\
	-lowerf 130 \
	-upperf 6800 \
	-nfilt 25 \
	-transform dct \
	-lifter 22 \
	-feat 1s_c_d_dd \
	-svspec 0-12/13-25/26-38 \
	-agc none \
	-cmn current \
	-varnorm no \
	-model ptm \
	-cmninit 40,3,-1 

Current configuration:
[NAME]		[DEFLT]		[VALUE]
-agc		none		none
-agcthresh	2.0		2.000000e+00
-alpha		0.97		9.700000e-01
-ceplen		13		13
-cmn		current		current
-cmninit	8.0		40,3,-1
-dither		no		no
-doublebw	no		no
-feat		1s_c_d_dd	1s_c_d_dd
-frate		100		100
-input_endian	little		little
-lda				
-ldadim		0		0
-lifter		0		22
-logspec	no		no
-lowerf		133.33334	1.300000e+02
-ncep		13		13
-nfft		512		2048
-nfilt		40		25
-remove_dc	no		no
-remove_noise	yes		yes
-remove_silence	yes		yes
-round_filters	yes		yes
-samprate	16000		1.600000e+04
-seed		-1		-1
-smoothspec	no		no
-svspec				0-12/13-25/26-38
-transform	legacy		dct
-unit_area	yes		yes
-upperf		6855.4976	6.800000e+03
-vad_postspeech	50		50
-vad_prespeech	10		10
-vad_threshold	2.0		2.000000e+00
-varnorm	no		no
-verbose	no		no
-warp_params			
-warp_type	inverse_linear	inverse_linear
-wlen		0.025625	2.562500e-02

INFO: acmod.c(252): Parsed model-specific feature parameters from /usr/local/share/pocketsphinx/model/en-us/en-us/feat.params
INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='current', VARNORM='no', AGC='none'
INFO: cmn.c(143): mean[0]= 12.00, mean[1..12]= 0.0
INFO: acmod.c(171): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /usr/local/share/pocketsphinx/model/en-us/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/share/pocketsphinx/model/en-us/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(206): Reading HMM transition probability matrices: /usr/local/share/pocketsphinx/model/en-us/en-us/transition_matrices
INFO: acmod.c(124): Attempting to use PTM computation module
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: /usr/local/share/pocketsphinx/model/en-us/en-us/means
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: /usr/local/share/pocketsphinx/model/en-us/en-us/variances
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(354): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/share/pocketsphinx/model/en-us/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(835): Maximum top-N: 4
INFO: phone_loop_search.c(115): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 137526 * 32 bytes (4297 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /usr/local/share/pocketsphinx/model/en-us/cmudict-en-us.dict
INFO: dict.c(213): Allocated 1007 KiB for strings, 1662 KiB for phones
INFO: dict.c(336): 133425 words read
INFO: dict.c(342): Reading filler dictionary: /usr/local/share/pocketsphinx/model/en-us/en-us/noisedict
INFO: dict.c(213): Allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(345): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 42672 bytes (41 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 42672 bytes (41 KiB) for single-phone word triphones
INFO: jsgf.c(691): Defined rule: <digits.zero>
INFO: jsgf.c(691): Defined rule: <digits.one>
INFO: jsgf.c(691): Defined rule: <digits.two>
INFO: jsgf.c(691): Defined rule: <digits.three>
INFO: jsgf.c(691): Defined rule: <digits.four>
INFO: jsgf.c(691): Defined rule: <digits.five>
INFO: jsgf.c(691): Defined rule: <digits.six>
INFO: jsgf.c(691): Defined rule: <digits.seven>
INFO: jsgf.c(691): Defined rule: <digits.eight>
INFO: jsgf.c(691): Defined rule: <digits.nine>
INFO: jsgf.c(691): Defined rule: <digits.digit>
INFO: jsgf.c(691): Defined rule: <digits.g00011>
INFO: jsgf.c(691): Defined rule: PUBLIC <digits.digits>
INFO: jsgf.c(359): Right recursion <digits.g00011> 2 => 0
INFO: fsg_model.c(215): Computing transitive closure for null transitions
INFO: fsg_model.c(277): 0 null transitions added
INFO: fsg_search.c(227): FSG(beam: -1080, pbeam: -1080, wbeam: -634; wip: -26, pip: 0)
INFO: fsg_model.c(428): Adding silence transitions for <sil> to FSG
INFO: fsg_model.c(448): Added 3 silence word transitions
INFO: fsg_model.c(428): Adding silence transitions for <sil> to FSG
INFO: fsg_model.c(448): Added 3 silence word transitions
INFO: fsg_model.c(428): Adding silence transitions for [NOISE] to FSG
INFO: fsg_model.c(448): Added 3 silence word transitions
INFO: fsg_search.c(174): Added 14 alternate word transitions
INFO: fsg_lextree.c(110): Allocated 258 bytes (0 KiB) for left and right context phones
INFO: fsg_lextree.c(256): 331 HMM nodes in lextree (292 leaves)
INFO: fsg_lextree.c(259): Allocated 47664 bytes (46 KiB) for all lextree nodes
INFO: fsg_lextree.c(262): Allocated 42048 bytes (41 KiB) for lextree leafnodes

/home/sean/work/node-pocketsphinx/demo/index.js:24
	sphinx.addGrammarSearch('digits', __dirname + '/digits.gram');
	       ^
Error: Failed to add grammar search to recognizer
    at Namespace.<anonymous> (/home/sean/work/node-pocketsphinx/demo/index.js:24:9)
    at Namespace.emit (events.js:95:17)
    at Namespace.emit (/home/sean/work/node-pocketsphinx/node_modules/socket.io/lib/namespace.js:205:10)
    at /home/sean/work/node-pocketsphinx/node_modules/socket.io/lib/namespace.js:172:14
    at process._tickCallback (node.js:442:13)
sean@SeanUbuntu:~/work/node-pocketsphinx/demo$

**Comment by nshmyrev** [comment]
This issue was fixed in the last commit in https://github.com/cmusphinx/node-pocketsphinx

**Comment by nshmyrev** [comment]
And you are reporting to the wrong repository, this one is pretty outdated.

**Comment by seandoyle** [comment]
Thanks. I'll try again :-).

**Comment by seandoyle** [comment]
Yes - I was confused by the lack of an ‘issues’ link on the page
https://github.com/cmusphinx/node-pocketsphinx
and I must have accidentally clicked on the older repository.

It builds and starts fine now - I’m having trouble with both FireFox and Chrome getting input from the microphone but it could well be the machine I’m on. I will try to isolate this further.

What would be the best way to report issues?

Thanks so much.

Sean

On Feb 18, 2015, at 5:19 PM, Nickolay V. Shmyrev <notifications@github.com<mailto:notifications@github.com>> wrote:


And you are reporting to the wrong repository, this one is pretty outdated.

—
Reply to this email directly or view it on GitHub<https://github.com/moneppo/node-pocketsphinx/issues/6#issuecomment-74960753>.



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by nshmyrev** [comment]
I enabled issues in cmusphinx/node-pocketsphinx, please report any bugs you met there.

**Comment by seandoyle** [comment]
Thanks again!

On Feb 18, 2015, at 6:19 PM, Nickolay V. Shmyrev <notifications@github.com<mailto:notifications@github.com>> wrote:


I enabled issues in cmusphinx/node-pocketsphinx, please report any bugs you met there.

—
Reply to this email directly or view it on GitHub<https://github.com/moneppo/node-pocketsphinx/issues/6#issuecomment-74970020>.



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.
